server:
  port: 80

spring:
  application:
    name: cloud-orderby-service

eureka:
  client:
    register-with-eureka: true #true表示向注册中心注册自己
    fetch-registry: true #true自己不是注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/